#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# accueil:
#     path: /accueilController
#     controller: App\controller\accueilController::accueil

app_logout :
    path : /logout